import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { db } from '../firebase';

const sampleColleges = [
  {
    name: "Indian Institute of Technology Delhi",
    type: "Engineering",
    location: "Delhi, India",
    country: "India",
    state: "Delhi",
    city: "New Delhi",
    fees: 200000,
    currency: "INR",
    minCGPA: 8.5,
    ranking: 1,
    placementRate: 95,
    description: "Premier engineering institution known for excellence in technology and research. IIT Delhi is one of the top engineering colleges in India.",
    facilities: "World-class laboratories, Libraries, Sports complex, Hostels, Wi-Fi campus, Medical facilities",
    scholarships: "Merit-based scholarships, Need-based financial aid, Research fellowships",
    accreditation: "NAAC A++, NBA Accredited",
    contact: "+91-11-26591999",
    email: "info@iitd.ac.in",
    website: "https://home.iitd.ac.in"
  },
  {
    name: "Indian Institute of Technology Bombay",
    type: "Engineering",
    location: "Mumbai, India",
    country: "India",
    state: "Maharashtra",
    city: "Mumbai",
    fees: 215000,
    currency: "INR",
    minCGPA: 8.5,
    ranking: 2,
    placementRate: 96,
    description: "Leading technical institute with strong industry connections and research programs.",
    facilities: "Advanced labs, Central library, Sports facilities, Hostels, Research centers",
    scholarships: "Merit scholarships, SC/ST scholarships, Financial assistance programs",
    accreditation: "NAAC A++, NBA Accredited",
    contact: "+91-22-25722545",
    email: "info@iitb.ac.in",
    website: "https://www.iitb.ac.in"
  },
  {
    name: "Indian Institute of Technology Madras",
    type: "Engineering",
    location: "Chennai, India",
    country: "India",
    state: "Tamil Nadu",
    city: "Chennai",
    fees: 200000,
    currency: "INR",
    minCGPA: 8.5,
    ranking: 3,
    placementRate: 94,
    description: "Top-ranked IIT with strong focus on innovation and entrepreneurship.",
    facilities: "Research labs, Library, Sports complex, Hostels, Incubation center",
    scholarships: "Merit-based aid, Research assistantships, Government scholarships",
    accreditation: "NAAC A++, NBA Accredited",
    contact: "+91-44-22574000",
    email: "info@iitm.ac.in",
    website: "https://www.iitm.ac.in"
  },
  {
    name: "BITS Pilani",
    type: "Engineering",
    location: "Pilani, India",
    country: "India",
    state: "Rajasthan",
    city: "Pilani",
    fees: 450000,
    currency: "INR",
    minCGPA: 8.0,
    ranking: 5,
    placementRate: 92,
    description: "Premier private engineering institution with multiple campuses across India.",
    facilities: "Modern labs, Digital library, Sports facilities, Hostels, Innovation center",
    scholarships: "Merit-cum-need scholarships, Fee waivers for deserving students",
    accreditation: "NAAC A, NBA Accredited",
    contact: "+91-1596-242210",
    email: "info@pilani.bits-pilani.ac.in",
    website: "https://www.bits-pilani.ac.in"
  },
  {
    name: "Delhi Technological University",
    type: "Engineering",
    location: "Delhi, India",
    country: "India",
    state: "Delhi",
    city: "New Delhi",
    fees: 175000,
    currency: "INR",
    minCGPA: 7.5,
    ranking: 8,
    placementRate: 88,
    description: "State university offering quality engineering education with strong industry ties.",
    facilities: "Well-equipped labs, Library, Sports ground, Hostels, Training cell",
    scholarships: "Government scholarships, Merit scholarships, Fee concessions",
    accreditation: "NAAC A+, NBA Accredited",
    contact: "+91-11-27871023",
    email: "info@dtu.ac.in",
    website: "https://www.dtu.ac.in"
  },
  {
    name: "Netaji Subhas University of Technology",
    type: "Engineering",
    location: "Delhi, India",
    country: "India",
    state: "Delhi",
    city: "New Delhi",
    fees: 150000,
    currency: "INR",
    minCGPA: 7.5,
    ranking: 10,
    placementRate: 85,
    description: "Renowned engineering college with focus on research and innovation.",
    facilities: "Modern laboratories, Central library, Sports complex, Hostels",
    scholarships: "SC/ST scholarships, Merit-based awards, Financial assistance",
    accreditation: "NAAC A, NBA Accredited",
    contact: "+91-11-25000568",
    email: "info@nsut.ac.in",
    website: "https://www.nsut.ac.in"
  },
  {
    name: "Indian Institute of Management Ahmedabad",
    type: "Management",
    location: "Ahmedabad, India",
    country: "India",
    state: "Gujarat",
    city: "Ahmedabad",
    fees: 2500000,
    currency: "INR",
    minCGPA: 8.0,
    ranking: 1,
    placementRate: 100,
    description: "Premier management institute with world-class faculty and global recognition.",
    facilities: "Smart classrooms, Case study rooms, Library, Sports facilities, Hostels",
    scholarships: "Need-based financial aid, Merit scholarships, Loan assistance",
    accreditation: "AACSB, EQUIS, AMBA accredited",
    contact: "+91-79-71524478",
    email: "info@iima.ac.in",
    website: "https://www.iima.ac.in"
  },
  {
    name: "Indian Institute of Management Bangalore",
    type: "Management",
    location: "Bangalore, India",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    fees: 2400000,
    currency: "INR",
    minCGPA: 8.0,
    ranking: 2,
    placementRate: 100,
    description: "Top B-school known for academic excellence and strong industry connections.",
    facilities: "Modern classrooms, Research centers, Library, Gym, Hostels",
    scholarships: "Merit scholarships, Financial aid programs, Education loans",
    accreditation: "AACSB, Association of MBAs accredited",
    contact: "+91-80-26993000",
    email: "info@iimb.ac.in",
    website: "https://www.iimb.ac.in"
  },
  {
    name: "All India Institute of Medical Sciences Delhi",
    type: "Medical",
    location: "Delhi, India",
    country: "India",
    state: "Delhi",
    city: "New Delhi",
    fees: 5000,
    currency: "INR",
    minCGPA: 9.0,
    ranking: 1,
    placementRate: 100,
    description: "Premier medical institute offering world-class medical education and healthcare.",
    facilities: "Super-specialty hospitals, Research labs, Library, Hostels, Sports complex",
    scholarships: "Government scholarships, Merit-based aid, Fee waivers",
    accreditation: "MCI approved, NAAC A++",
    contact: "+91-11-26588500",
    email: "info@aiims.edu",
    website: "https://www.aiims.edu"
  },
  {
    name: "National Law School of India University",
    type: "Law",
    location: "Bangalore, India",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    fees: 250000,
    currency: "INR",
    minCGPA: 8.5,
    ranking: 1,
    placementRate: 98,
    description: "India's premier law school with excellent faculty and judicial training.",
    facilities: "Moot court halls, Legal aid clinics, Library, Hostels, Sports facilities",
    scholarships: "Merit-based scholarships, Need-based financial aid, Fee waivers",
    accreditation: "Bar Council of India approved, NAAC A++",
    contact: "+91-80-23160532",
    email: "info@nls.ac.in",
    website: "https://www.nls.ac.in"
  },
  {
    name: "St. Stephen's College",
    type: "Arts",
    location: "Delhi, India",
    country: "India",
    state: "Delhi",
    city: "New Delhi",
    fees: 50000,
    currency: "INR",
    minCGPA: 7.5,
    ranking: 1,
    placementRate: 85,
    description: "Premier liberal arts college affiliated with Delhi University.",
    facilities: "Well-stocked library, Laboratories, Sports ground, Hostels, Auditorium",
    scholarships: "Merit scholarships, Minority scholarships, Financial assistance",
    accreditation: "NAAC A++, UGC recognized",
    contact: "+91-11-27667296",
    email: "principal@ststephens.edu",
    website: "https://www.ststephens.edu"
  },
  {
    name: "Indian Institute of Science",
    type: "Science",
    location: "Bangalore, India",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    fees: 50000,
    currency: "INR",
    minCGPA: 9.0,
    ranking: 1,
    placementRate: 95,
    description: "Premier research institution for science and engineering.",
    facilities: "State-of-art research labs, Library, Computing facilities, Hostels, Sports",
    scholarships: "Research fellowships, Merit scholarships, INSPIRE scholarships",
    accreditation: "NAAC A++, Deemed University",
    contact: "+91-80-22932000",
    email: "office@iisc.ac.in",
    website: "https://www.iisc.ac.in"
  },
  {
    name: "National Institute of Technology Trichy",
    type: "Engineering",
    location: "Trichy, India",
    country: "India",
    state: "Tamil Nadu",
    city: "Tiruchirappalli",
    fees: 165000,
    currency: "INR",
    minCGPA: 7.5,
    ranking: 6,
    placementRate: 90,
    description: "Premier NIT with excellent academic programs and placement records.",
    facilities: "Modern labs, Central library, Sports complex, Hostels, Wi-Fi campus",
    scholarships: "Government scholarships, Merit awards, Fee concessions",
    accreditation: "NAAC A++, NBA Accredited",
    contact: "+91-431-2503000",
    email: "dir@nitt.edu",
    website: "https://www.nitt.edu"
  },
  {
    name: "Vellore Institute of Technology",
    type: "Engineering",
    location: "Vellore, India",
    country: "India",
    state: "Tamil Nadu",
    city: "Vellore",
    fees: 200000,
    currency: "INR",
    minCGPA: 7.0,
    ranking: 12,
    placementRate: 87,
    description: "Large private university with strong industry partnerships and placements.",
    facilities: "Advanced labs, Digital library, Sports facilities, Hostels, Innovation center",
    scholarships: "Merit-based scholarships, Sports scholarships, Financial aid",
    accreditation: "NAAC A++, NBA Accredited",
    contact: "+91-416-2202000",
    email: "info@vit.ac.in",
    website: "https://www.vit.ac.in"
  },
  {
    name: "Manipal Institute of Technology",
    type: "Engineering",
    location: "Manipal, India",
    country: "India",
    state: "Karnataka",
    city: "Manipal",
    fees: 350000,
    currency: "INR",
    minCGPA: 7.0,
    ranking: 15,
    placementRate: 85,
    description: "Well-established private engineering college with global collaborations.",
    facilities: "Modern infrastructure, Research centers, Library, Sports complex, Hostels",
    scholarships: "Merit scholarships, Need-based aid, Sports scholarships",
    accreditation: "NAAC A, NBA Accredited",
    contact: "+91-820-2925100",
    email: "mit@manipal.edu",
    website: "https://manipal.edu/mit.html"
  },
  {
    name: "Malla Reddy University",
    type: "Engineering",
    types: ["Engineering", "Management", "Medical", "Pharmacy"],
    location: "Hyderabad, India",
    country: "India",
    state: "Telangana",
    city: "Hyderabad",
    fees: 185000,
    currency: "INR",
    minCGPA: 6.0,
    ranking: 45,
    placementRate: 82,
    description: "Private university in Hyderabad offering diverse programs in Engineering, Management, Medical Sciences and Pharmacy. Known for industry-oriented curriculum and strong placement support.",
    facilities: "Modern labs, Central Library, Sports complex, Hostels, Medical center, Wi-Fi campus",
    scholarships: "Merit-based scholarships, SC/ST fee concessions, Sports scholarships, Need-based aid",
    accreditation: "NAAC A, UGC recognized, AICTE approved",
    contact: "+91-40-23134455",
    email: "info@mallareddyuniversity.ac.in",
    website: "https://www.mallareddyuniversity.ac.in"
  },

  // ── ABROAD — Engineering ──────────────────────────────────────────────────
  {
    name: "Massachusetts Institute of Technology (MIT)",
    type: "Engineering",
    location: "Cambridge, USA",
    country: "USA",
    state: "Massachusetts",
    city: "Cambridge",
    fees: 57986,
    currency: "USD",
    minCGPA: 9.5,
    ranking: 1,
    placementRate: 97,
    description: "World's top engineering and technology university renowned for cutting-edge research, innovation, and producing Nobel laureates and industry leaders.",
    facilities: "State-of-the-art labs, Infinite Corridor, Stata Center, Sports facilities, Dorms, Medical center",
    scholarships: "Need-blind admissions, MIT Scholarship, Merit fellowships, Research assistantships",
    accreditation: "NEASC accredited, ABET accredited programs",
    contact: "+1-617-253-1000",
    email: "admissions@mit.edu",
    website: "https://www.mit.edu"
  },
  {
    name: "Stanford University",
    type: "Engineering",
    location: "Stanford, USA",
    country: "USA",
    state: "California",
    city: "Stanford",
    fees: 62484,
    currency: "USD",
    minCGPA: 9.5,
    ranking: 2,
    placementRate: 96,
    description: "Silicon Valley's premier engineering institution with deep connections to the tech industry and a culture of entrepreneurship and innovation.",
    facilities: "SLAC, d.school, Engineering Quad, Green Library, Maples Pavilion, Research parks",
    scholarships: "Stanford Financial Aid, Knight-Hennessy Scholars, Research fellowships",
    accreditation: "WASC Senior College and University Commission",
    contact: "+1-650-723-2300",
    email: "admission@stanford.edu",
    website: "https://www.stanford.edu"
  },
  {
    name: "University of Cambridge",
    type: "Engineering",
    location: "Cambridge, UK",
    country: "UK",
    state: "England",
    city: "Cambridge",
    fees: 35000,
    currency: "GBP",
    minCGPA: 9.0,
    ranking: 3,
    placementRate: 95,
    description: "One of the world's oldest and most prestigious universities, with a world-leading Engineering department and a rich culture of scientific discovery.",
    facilities: "Cavendish Laboratory, Engineering Design Centre, Libraries, Colleges, Sports grounds",
    scholarships: "Cambridge Trust Scholarships, Gates Cambridge Scholarships, College bursaries",
    accreditation: "UK Quality Assurance Agency, Engineering Council",
    contact: "+44-1223-337733",
    email: "admissions@cam.ac.uk",
    website: "https://www.cam.ac.uk"
  },
  {
    name: "ETH Zurich",
    type: "Engineering",
    location: "Zurich, Switzerland",
    country: "Switzerland",
    state: "Zürich Canton",
    city: "Zurich",
    fees: 730,
    currency: "CHF",
    minCGPA: 8.5,
    ranking: 7,
    placementRate: 94,
    description: "Europe's leading science and technology university, with 21 Nobel Prize winners among its alumni and faculty. Exceptionally low tuition fees make it a top choice.",
    facilities: "Innovation Park, Quantum Computing labs, Library, Sports centre, Maker space",
    scholarships: "ETH Excellence Scholarship, Swiss Government Excellence Scholarships",
    accreditation: "Swiss Accreditation Council, EUR-ACE label",
    contact: "+41-44-632-1111",
    email: "admissions@ethz.ch",
    website: "https://www.ethz.ch"
  },
  {
    name: "Carnegie Mellon University",
    type: "Engineering",
    location: "Pittsburgh, USA",
    country: "USA",
    state: "Pennsylvania",
    city: "Pittsburgh",
    fees: 60932,
    currency: "USD",
    minCGPA: 9.0,
    ranking: 5,
    placementRate: 95,
    description: "Global leader in computer science, robotics, and artificial intelligence with a unique blend of technical rigor and creative problem-solving.",
    facilities: "Robotics Institute, SCS Gates Center, Libraries, CFA, Sports complex",
    scholarships: "Presidential Scholarship, Andrew Carnegie Society Awards, Graduate fellowships",
    accreditation: "Middle States Commission, ABET accredited programs",
    contact: "+1-412-268-2000",
    email: "admission@cmu.edu",
    website: "https://www.cmu.edu"
  },
  {
    name: "University of Toronto",
    type: "Engineering",
    location: "Toronto, Canada",
    country: "Canada",
    state: "Ontario",
    city: "Toronto",
    fees: 58160,
    currency: "CAD",
    minCGPA: 8.0,
    ranking: 18,
    placementRate: 91,
    description: "Canada's top university offering world-class engineering education with strong ties to Toronto's growing tech ecosystem.",
    facilities: "Myhal Centre for Engineering Innovation, Fields Institute, Libraries, Athletic Centre",
    scholarships: "Lester B. Pearson International Scholarship, University of Toronto Scholar, OGS",
    accreditation: "Engineers Canada (CEAB) accredited",
    contact: "+1-416-978-2011",
    email: "admissions.engineering@utoronto.ca",
    website: "https://engineering.utoronto.ca"
  },
  {
    name: "National University of Singapore (NUS)",
    type: "Engineering",
    location: "Singapore",
    country: "Singapore",
    state: "Central Region",
    city: "Singapore",
    fees: 17550,
    currency: "SGD",
    minCGPA: 8.5,
    ranking: 8,
    placementRate: 93,
    description: "Asia's top university with a globally connected engineering faculty and strong research-industry partnerships in the heart of Asia's tech hub.",
    facilities: "i4.0 NUS Learning Factory, E-Fab, University Cultural Centre, Libraries, Sports Hall",
    scholarships: "NUS Merit Scholarship, ASEAN Undergraduate Scholarship, Research Scholarships",
    accreditation: "Engineering Accreditation Board Singapore",
    contact: "+65-6516-6666",
    email: "askadmissions@nus.edu.sg",
    website: "https://cde.nus.edu.sg"
  },
  {
    name: "Technical University of Munich (TUM)",
    type: "Engineering",
    location: "Munich, Germany",
    country: "Germany",
    state: "Bavaria",
    city: "Munich",
    fees: 144,
    currency: "EUR",
    minCGPA: 8.0,
    ranking: 30,
    placementRate: 92,
    description: "Germany's top technical university offering almost tuition-free world-class engineering education with exceptional industry connections.",
    facilities: "TUM Campus, Garching research labs, Munich Robotics lab, Sports University",
    scholarships: "DAAD Scholarship, Deutschland Stipendium, TUM Global Incentive Fund",
    accreditation: "ASIIN, ABET, EUR-ACE accredited",
    contact: "+49-89-289-01",
    email: "studium@tum.de",
    website: "https://www.tum.de"
  },

  // ── ABROAD — Management ───────────────────────────────────────────────────
  {
    name: "Harvard Business School",
    type: "Management",
    location: "Boston, USA",
    country: "USA",
    state: "Massachusetts",
    city: "Boston",
    fees: 73440,
    currency: "USD",
    minCGPA: 8.5,
    ranking: 1,
    placementRate: 99,
    description: "The world's most prestigious MBA program, known for the case-study method, unparalleled alumni network, and producing global business leaders.",
    facilities: "Aldrich Hall, Baker Library, Bloomberg Center, Executive Education, HBS Gym",
    scholarships: "HBS Fellowships, Need-based aid, Harvard Grants",
    accreditation: "AACSB, NEASC",
    contact: "+1-617-495-6000",
    email: "admissions@hbs.edu",
    website: "https://www.hbs.edu"
  },
  {
    name: "London Business School",
    type: "Management",
    location: "London, UK",
    country: "UK",
    state: "England",
    city: "London",
    fees: 99400,
    currency: "GBP",
    minCGPA: 8.0,
    ranking: 4,
    placementRate: 98,
    description: "Europe's premier business school at the heart of London's global financial district, offering exceptional MBA and Masters programs.",
    facilities: "Sussex Place Campus, Bloomberg Centre, Library, Career Centre, Social spaces",
    scholarships: "LBS Scholarship, Regional Scholarships, Forté Fellowship, Forte Foundation",
    accreditation: "AACSB, EQUIS, AMBA",
    contact: "+44-20-7000-7000",
    email: "mbainfo@london.edu",
    website: "https://www.london.edu"
  },
  {
    name: "INSEAD",
    type: "Management",
    location: "Fontainebleau, France",
    country: "France",
    state: "Île-de-France",
    city: "Fontainebleau",
    fees: 95000,
    currency: "EUR",
    minCGPA: 8.0,
    ranking: 3,
    placementRate: 97,
    description: "The Business School for the World — a truly international MBA spanning campuses in France, Singapore, and Abu Dhabi with a diverse global student body.",
    facilities: "Chateau campus, Singapore campus, Bloomberg Trading Room, Libraries, Recreation",
    scholarships: "INSEAD Scholarships, Regional Awards, Women's Scholarships, Forte Fellowship",
    accreditation: "AACSB, EQUIS, AMBA",
    contact: "+33-1-60-72-40-00",
    email: "mba.info@insead.edu",
    website: "https://www.insead.edu"
  },
  {
    name: "Wharton School, University of Pennsylvania",
    type: "Management",
    location: "Philadelphia, USA",
    country: "USA",
    state: "Pennsylvania",
    city: "Philadelphia",
    fees: 86710,
    currency: "USD",
    minCGPA: 8.5,
    ranking: 2,
    placementRate: 99,
    description: "The world's first collegiate business school, offering the most rigorous MBA curriculum with strengths in finance, analytics, and entrepreneurship.",
    facilities: "Huntsman Hall, Jon M. Huntsman Hall, Steinberg-Dietrich Hall, Libraries, Gyms",
    scholarships: "Wharton Fellowships, Joseph Wharton Scholarship, University Fellowships",
    accreditation: "AACSB, Middle States Commission",
    contact: "+1-215-898-0100",
    email: "mba.admissions@wharton.upenn.edu",
    website: "https://www.wharton.upenn.edu"
  },

  // ── ABROAD — Medical ─────────────────────────────────────────────────────
  {
    name: "Johns Hopkins University",
    type: "Medical",
    location: "Baltimore, USA",
    country: "USA",
    state: "Maryland",
    city: "Baltimore",
    fees: 63600,
    currency: "USD",
    minCGPA: 9.5,
    ranking: 1,
    placementRate: 98,
    description: "World-renowned medical school consistently ranked #1 in the USA for research, clinical training, and public health education.",
    facilities: "Johns Hopkins Hospital, Bloomberg School of Public Health, Welch Library, Simulation Center",
    scholarships: "Financial aid programs, Research fellowships, Hopkins Scholarship",
    accreditation: "LCME, Middle States Commission",
    contact: "+1-410-955-3182",
    email: "somadmissions@jhmi.edu",
    website: "https://www.hopkinsmedicine.org/som"
  },
  {
    name: "University of Oxford – Medical Sciences",
    type: "Medical",
    location: "Oxford, UK",
    country: "UK",
    state: "England",
    city: "Oxford",
    fees: 37310,
    currency: "GBP",
    minCGPA: 9.5,
    ranking: 2,
    placementRate: 99,
    description: "Oxford's Medical Sciences Division is one of the world's leading centres for biomedical research and clinical training, blending deep science with patient care.",
    facilities: "John Radcliffe Hospital, Nuffield Orthopaedic Centre, Wellcome Trust Centre, Bodleian Health Care Libraries",
    scholarships: "Clarendon Scholarships, Wellcome Trust Scholarships, Oxford-Weidenfeld Scholarships",
    accreditation: "General Medical Council (GMC) approved",
    contact: "+44-1865-270207",
    email: "medsci.admissions@ox.ac.uk",
    website: "https://www.medsci.ox.ac.uk"
  },
  {
    name: "Karolinska Institute",
    type: "Medical",
    location: "Stockholm, Sweden",
    country: "Sweden",
    state: "Stockholm County",
    city: "Stockholm",
    fees: 90000,
    currency: "SEK",
    minCGPA: 9.0,
    ranking: 7,
    placementRate: 97,
    description: "One of the world's most prestigious medical universities, responsible for awarding the Nobel Prize in Physiology or Medicine, with cutting-edge biomedical research.",
    facilities: "Karolinska University Hospital, ANA Futura labs, Biomedicum, Campus library",
    scholarships: "Swedish Institute Scholarships, KI Scholarships, Erasmus+ funding",
    accreditation: "Swedish Higher Education Authority (UKÄ)",
    contact: "+46-8-524-860-00",
    email: "study@ki.se",
    website: "https://ki.se"
  },
  {
    name: "University of Melbourne – Medicine",
    type: "Medical",
    location: "Melbourne, Australia",
    country: "Australia",
    state: "Victoria",
    city: "Melbourne",
    fees: 96000,
    currency: "AUD",
    minCGPA: 9.0,
    ranking: 10,
    placementRate: 96,
    description: "Australia's top medical school offering MD and research programs backed by the Melbourne Academic Medical Centre and world-class teaching hospitals.",
    facilities: "Royal Melbourne Hospital, Melbourne Medical School, Doherty Institute, Bio21 Institute",
    scholarships: "Melbourne International Fee Remission Scholarship, Graduate Access Melbourne",
    accreditation: "Australian Medical Council (AMC) accredited",
    contact: "+61-3-8344-5890",
    email: "medicine-admissions@unimelb.edu.au",
    website: "https://medicine.unimelb.edu.au"
  },

  // ── ABROAD — Law ─────────────────────────────────────────────────────────
  {
    name: "Yale Law School",
    type: "Law",
    location: "New Haven, USA",
    country: "USA",
    state: "Connecticut",
    city: "New Haven",
    fees: 74800,
    currency: "USD",
    minCGPA: 9.5,
    ranking: 1,
    placementRate: 99,
    description: "America's most selective law school, producing Supreme Court Justices, presidents, and leading legal scholars renowned for academic freedom and public interest law.",
    facilities: "Sterling Law Building, Lillian Goldman Law Library, Moot Court rooms, Law clinics",
    scholarships: "YLS Loan Repayment Assistance, Merit scholarships, Public Interest Fellowships",
    accreditation: "American Bar Association (ABA) approved",
    contact: "+1-203-432-4995",
    email: "admissions.law@yale.edu",
    website: "https://law.yale.edu"
  },
  {
    name: "University of Oxford – Faculty of Law",
    type: "Law",
    location: "Oxford, UK",
    country: "UK",
    state: "England",
    city: "Oxford",
    fees: 30000,
    currency: "GBP",
    minCGPA: 9.0,
    ranking: 2,
    placementRate: 98,
    description: "One of the world's oldest and most esteemed law faculties, offering the BCL and MLF programs that attract the brightest legal minds from across the globe.",
    facilities: "Bodleian Law Library, Moot Court, Oxford Law Faculty Building, College libraries",
    scholarships: "Clarendon Fund, Chevening Scholarships, US Oxford Scholarships",
    accreditation: "Solicitors Regulation Authority, Bar Standards Board",
    contact: "+44-1865-271490",
    email: "law.admissions@law.ox.ac.uk",
    website: "https://www.law.ox.ac.uk"
  },
  {
    name: "New York University School of Law",
    type: "Law",
    location: "New York, USA",
    country: "USA",
    state: "New York",
    city: "New York",
    fees: 72416,
    currency: "USD",
    minCGPA: 9.0,
    ranking: 6,
    placementRate: 97,
    description: "A global centre of legal education in the heart of New York City, with particular strengths in international law, tax law, and corporate law.",
    facilities: "Vanderbilt Hall, D'Agostino Hall, Hauser Global Law School, Law clinics, Library",
    scholarships: "Root-Tilden-Kern Scholarships, NYU Law Scholarships, Public Interest Stipends",
    accreditation: "American Bar Association (ABA) approved",
    contact: "+1-212-998-6060",
    email: "law.moreinfo@nyu.edu",
    website: "https://www.law.nyu.edu"
  },

  // ── ABROAD — Science ─────────────────────────────────────────────────────
  {
    name: "California Institute of Technology (Caltech)",
    type: "Science",
    location: "Pasadena, USA",
    country: "USA",
    state: "California",
    city: "Pasadena",
    fees: 60816,
    currency: "USD",
    minCGPA: 9.5,
    ranking: 2,
    placementRate: 96,
    description: "The world's elite science and engineering research university producing more Nobel laureates per capita than any other institution, home to NASA's Jet Propulsion Laboratory.",
    facilities: "JPL, Cahill Center, Keck Observatory, Millikan Library, Beckman Institute",
    scholarships: "Need-based financial aid, Caltech Scholarship, JPL Internships",
    accreditation: "WASC Senior College and University Commission, ABET",
    contact: "+1-626-395-6811",
    email: "ugadmissions@caltech.edu",
    website: "https://www.caltech.edu"
  },
  {
    name: "University of Edinburgh",
    type: "Science",
    location: "Edinburgh, UK",
    country: "UK",
    state: "Scotland",
    city: "Edinburgh",
    fees: 29600,
    currency: "GBP",
    minCGPA: 8.0,
    ranking: 25,
    placementRate: 91,
    description: "One of the UK's ancient universities with world-class science faculties in biological sciences, chemistry, physics, and informatics in a historic city.",
    facilities: "King's Buildings Campus, Informatics Forum, Easter Bush Campus, Main University Library",
    scholarships: "Edinburgh Scholarship, Principal's Career Development PhD Scholarship, Global Scholarships",
    accreditation: "Quality Assurance Agency for Higher Education (QAA)",
    contact: "+44-131-650-1000",
    email: "scieng.admissions@ed.ac.uk",
    website: "https://www.ed.ac.uk/science-engineering"
  },
  {
    name: "University of British Columbia",
    type: "Science",
    location: "Vancouver, Canada",
    country: "Canada",
    state: "British Columbia",
    city: "Vancouver",
    fees: 42050,
    currency: "CAD",
    minCGPA: 8.0,
    ranking: 34,
    placementRate: 90,
    description: "Canada's third-largest research university with outstanding science programs set on a spectacular oceanside campus, offering strong research and co-op opportunities.",
    facilities: "TRIUMF, Life Sciences Centre, Main Library, Aquatic Centre, Pacific Museum of the Earth",
    scholarships: "International Major Entrance Scholarship, UBC Centennial Scholars, NSERC",
    accreditation: "British Columbia Ministry of Advanced Education",
    contact: "+1-604-822-2211",
    email: "science.advising@ubc.ca",
    website: "https://science.ubc.ca"
  },

  // ── ABROAD — Arts & Humanities ────────────────────────────────────────────
  {
    name: "University of Oxford – Humanities",
    type: "Arts",
    location: "Oxford, UK",
    country: "UK",
    state: "England",
    city: "Oxford",
    fees: 28950,
    currency: "GBP",
    minCGPA: 9.0,
    ranking: 1,
    placementRate: 93,
    description: "The world's gold standard for humanities education, with programmes in literature, philosophy, history, fine art, and music spanning eight centuries of scholarship.",
    facilities: "Bodleian Libraries, Ashmolean Museum, Sheldonian Theatre, Oxford Union, College libraries",
    scholarships: "Rhodes Scholarship, Clarendon Scholarship, Chevening Awards",
    accreditation: "Quality Assurance Agency for Higher Education (QAA)",
    contact: "+44-1865-270000",
    email: "humanities@ox.ac.uk",
    website: "https://www.humanities.ox.ac.uk"
  },
  {
    name: "New York University (NYU) – Tisch School of the Arts",
    type: "Arts",
    location: "New York, USA",
    country: "USA",
    state: "New York",
    city: "New York",
    fees: 60438,
    currency: "USD",
    minCGPA: 7.5,
    ranking: 3,
    placementRate: 88,
    description: "The nation's foremost arts school in the cultural capital of the world, producing successful filmmakers, actors, writers, and digital media creators.",
    facilities: "Tisch Broadway Productions, film studios, performance spaces, editing suites, galleries",
    scholarships: "Tisch School Scholarships, NYU Need-based Aid, Dean's Awards",
    accreditation: "Middle States Commission on Higher Education, NASD",
    contact: "+1-212-998-1800",
    email: "tisch.special.info@nyu.edu",
    website: "https://tisch.nyu.edu"
  },
  {
    name: "London School of Economics and Political Science (LSE)",
    type: "Arts",
    location: "London, UK",
    country: "UK",
    state: "England",
    city: "London",
    fees: 24408,
    currency: "GBP",
    minCGPA: 8.0,
    ranking: 5,
    placementRate: 94,
    description: "The world-leading social science university, specialising in economics, political science, sociology, law, and international relations, shaping global policy and debate.",
    facilities: "Lionel Robbins Library, Shaw Library, Student Centre, Peacock Theatre, Alumni Garden",
    scholarships: "LSE Scholarships, Chevening, Commonwealth Scholarships, George Webb Medley Scholarship",
    accreditation: "Quality Assurance Agency for Higher Education (QAA)",
    contact: "+44-20-7405-7686",
    email: "ug.admissions@lse.ac.uk",
    website: "https://www.lse.ac.uk"
  },
  {
    name: "Sciences Po Paris",
    type: "Arts",
    location: "Paris, France",
    country: "France",
    state: "Île-de-France",
    city: "Paris",
    fees: 14000,
    currency: "EUR",
    minCGPA: 7.5,
    ranking: 10,
    placementRate: 89,
    description: "France's leading social sciences university, globally recognised for political science, international affairs, law, and journalism in the heart of Paris.",
    facilities: "Richard Descoings Library, 7 campuses, Digital Learning Centre, Student House",
    scholarships: "Sciences Po Scholarships, Émile Boutmy Scholarship, Eiffel Excellence Scholarship",
    accreditation: "Hcéres (French Higher Education Evaluation Agency)",
    contact: "+33-1-45-49-50-50",
    email: "info@sciencespo.fr",
    website: "https://www.sciencespo.fr"
  }
];

export const addSampleColleges = async () => {
  console.log('Starting to add sample colleges...');
  let successCount = 0;
  let errorCount = 0;

  for (const college of sampleColleges) {
    try {
      await addDoc(collection(db, 'colleges'), {
        ...college,
        createdAt: serverTimestamp(),
        source: 'Sample Data'
      });
      successCount++;
      console.log(`✓ Added: ${college.name}`);
    } catch (error) {
      errorCount++;
      console.error(`✗ Failed to add ${college.name}:`, error.message);
    }
  }

  console.log(`\nCompleted!`);
  console.log(`Success: ${successCount} colleges`);
  console.log(`Failed: ${errorCount} colleges`);
  
  return { successCount, errorCount };
};

// For direct import in browser console
if (typeof window !== 'undefined') {
  window.addSampleColleges = addSampleColleges;
}

export default addSampleColleges;
